# Modify name if deploying multiple instances
name = "sub-box"

main = ".open-next/worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

# [placement]
# mode = "smart"

# Environment variables
# Modify these to use the correct environment variables
[vars]
ADMIN_USERNAME = "leeflour"
ADMIN_PASSWORD = "l2332853284" # Change this to a secure password
JWT_SECRET = "qaMdhfkeE7CLk7px9gTKKmHENo1oFzhe" # Change this to a secure secret key
SESSION_TAG = "0"
SESSION_DURATION = "7d"
DEPLOY_TARGET = "cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "subbox" # Change this to the name of your D1 database
database_id = "8161fd13-3a00-43d4-9d41-c12aff7bfbab" # wrangler d1 info <YOUR_DATABASE_NAME>

[observability.logs]
enabled = true

# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "prod-sub-box-next-inc-cache"
